### ISSUE TITLE
Secure Boot incorrectly detected

### ISSUE THREAD

**Issue by singlecheeze** [kubev2v/forklift#19]
With a brand new Windows 10 VM in vCenter 7.0.3.01000/ESXi, 7.0.3, 20328353 created with Secure Boot disabled in boot options, MTV always detects Secure Boot present on the VM.

![image](https://user-images.githubusercontent.com/12156213/196445396-96da1f0b-b110-42e9-b495-b467d3ce95f2.png)
![image](https://user-images.githubusercontent.com/12156213/196445582-47e48f5b-4f0f-4f35-b8ba-90a31f09eb93.png)

Upon successful migration, the only workaround is to attempt to boot the new VM in OpenShift, let Windows go into automatic repair, and manually disable secure boot.

![image](https://user-images.githubusercontent.com/12156213/196447144-9261c550-add2-4c65-b42f-0822a70c949f.png)
![image](https://user-images.githubusercontent.com/12156213/196447218-ce50e56d-dec1-4bb3-b8b4-4adfbc9e64a2.png)
![image](https://user-images.githubusercontent.com/12156213/196447338-571ea250-d836-48b3-b8ce-a5b373842ccb.png)
![image](https://user-images.githubusercontent.com/12156213/196447419-78d3673a-9a08-4339-a2fd-dcb5570fcc28.png)
![image](https://user-images.githubusercontent.com/12156213/196447493-1c8bab7d-f79b-4595-9e67-0eebd5a4872d.png)  
  
*NOTE: On the image above, the VM has already been rebooted successfully, after Windows 10 boot, with Secure Boot disabled. This is why the "Current Secure Boot State: Disabled". Typically, on first boot this will be Enabled erroneously.*

**Comment by ahadas** [comment]
@nyoxi @rwmjones  if I read it correctly, it seems that there's an assumption in our code that [getting UEFI from vSphere necessarily means that secure boot is enabled](https://github.com/kubev2v/forklift/blob/49aa17770c0b775a47e2b0c7868cdecd701e8641/validation/policies/io/konveyor/forklift/vmware/uefi_boot.rego#L3-L13). I see that in RHV we used to correct the firmware based on the output we got from virt-v2v (IIRC virt-v2v used to map UEFI+secure boot to the corresponding firmware in RHV and to BIOS otherwise) but forklift doesn't do that - does virt-v2v determine whether secure boot is enabled by inspecting the virtual disk(s)?

**Comment by rwmjones** [comment]
For RHV we comment on but don't ever set the Q35 + UEFI + SB combination:

https://github.com/libguestfs/virt-v2v/blob/2949109ff9f7a081b1a4b475b9f7bcbef5b45ee0/lib/create_ovf.ml#L465

For libvirt XML output it's a bit confusing.  We do set "secure boot" for some guests, but what is actually going on here is that libvirt forces us to choose a UEFI vars file and some hosts (eg. RHEL 7.3+) do not ship a UEFI vars file that doesn't have the secure boot (flag? keys?).  So in these cases we set <smm> in the libvirt XML because it's necessary to get the guest to boot, but otherwise I think it's completely ignored.

> does virt-v2v determine whether secure boot is enabled by inspecting the virtual disk(s)?

This is a very interesting question and I've no idea if it's possible.

However I will say that secure boot is designed to prevent the kind of conversions that virt-v2v is doing.  Without having a way to copy the virtual TPM state from VMware and create a compatible TPM on the KVM side (which AFAIK is impossible) SB guests will always have SB disabled on the target.  You'll have to enroll keys etc etc after conversion.  (The guests should still be bootable)

**Comment by nyoxi** [comment]
Given the state of the affairs this unlikely to be related to virt-v2v at all. Unless virt-v2v performs some special tweaks to the Windows guest OS itself (which I don't think it does). The way I see this there may be two separate bugs:

1) For some reason we don't distinguish between EFI with and without Secure Boot when source is VMware. Instead, EFI bios implies Secure Boot during validation. I don't know if we are able to tell from VMware metadata whether Secure Boot should or should not be enabled. This needs to be verified.

2) We don't set `secureBoot` flag when creating the VM in Kubevirt. We need to tell Kubevirt that secure boot is disabled (and not the other way around). And from what I see we don't do that. Because based on the [docs](https://kubevirt.io/user-guide/virtual_machines/virtual_hardware/#biosuefi):

    > Enabling EFI automatically enables [Secure Boot](https://docs.microsoft.com/en-us/windows-hardware/design/device-experiences/oem-secure-boot), unless the secureBoot field under efi is set to false.

**Comment by singlecheeze** [comment]
The one screenshot I'm missing is showing the VM settings in OCP. The Boot setting, on migration, defaults to EFI but NOT EFI (Secure) so in essence, there is another thing that needs to be synchronized: The EFI Secure boot setting in the actual BIOS of the post migration VM, and the console/yaml of the post migration VM

**Comment by ahadas** [comment]
@rwmjones ack, my memory really fooled me this time :)

> 1. For some reason we don't distinguish between EFI with and without Secure Boot when source is VMware. Instead, EFI bios implies Secure Boot during validation. I don't know if we are able to tell from VMware metadata whether Secure Boot should or should not be enabled. This needs to be verified.

Yeah, and if we can't determine this then we should probably change the aforementioned message ("UEFI secure boot is enabled. NVRAM data is not copied during the migration and thus the VM might not boot on OpenShift Virtualization."). I didn't realize that point, that we don't have an indication of whether secure boot is really enabled, when suggesting this message in https://github.com/kubev2v/forklift-validation/pull/46

> 2. We don't set `secureBoot` flag when creating the VM in Kubevirt. We need to tell Kubevirt that secure boot is disabled (and not the other way around). And from what I see we don't do that. Because based on the [docs](https://kubevirt.io/user-guide/virtual_machines/virtual_hardware/#biosuefi):
>    > Enabling EFI automatically enables [Secure Boot](https://docs.microsoft.com/en-us/windows-hardware/design/device-experiences/oem-secure-boot), unless the secureBoot field under efi is set to false.

+1
The downside is that if CNV enables secure-boot by default for EFI then we'll end up with configuration that is different than this  when importing a VM with EFI and secure-boot disabled but yeah, if secure boot was disabled on the source it makes sense to me to disable it also on the destination; and if secure boot was enabled on the source, the user would anyway need to disable it on the destination as pointed out above

> The one screenshot I'm missing is showing the VM settings in OCP. The Boot setting, on migration, defaults (Maybe, or this is an assumption as Secure Boot is disabled on the VMware side) to EFI but NOT EFI (Secure) so in essence, there is another thing that needs to be synchronized: The EFI Secure boot setting in the actual BIOS of the post migration VM, and the console/yaml of the post migration VM

@singlecheeze that's weird, I see in the yaml you posted on the gchat that the VM is set with:
```yaml
firmware:
  bootloader:
     efi: {}
  serial: 420184a6-1058-ca76-6a45-3f41664260e9
```
which aligns with what @nyoxi wrote above - maybe there's a bug in the OCP console that doesn't set `secureBoot` to false when  `NOT EFI (Secure)` appears in the VM settings?
