### ISSUE TITLE
Migrate VMs with LUKS-encrypted disks from vSphere

### ISSUE THREAD

**Issue by TylerGillson** [kubev2v/forklift#567]
Add support for specifying the `--key` flag for `virt-v2v` as per the [virt-v2v docs](https://www.libguestfs.org/virt-v2v.1.html):
![image](https://github.com/kubev2v/forklift/assets/1795270/32e8f9f5-4ae5-4258-9ee4-93f7da479cdc)

Possibly via an additional option in the `StorageMap` CRD?

**Comment by ahadas** [comment]
@TylerGillson thanks for filing this. we thought about it when trying to deal with TPM - we don't have a way to get it from RHV and even if we get it from vSphere, it would probably not give us much. so asking users to specify it and use it this way would make sense, but it means that it's something the user would need to specify likely per-VM (assuming different VMs use different keys)..

you propose to store it in the storage map because you saw a case that the keys are different for different datastores on the source environment? I'm ok with taking an assumption that the keys are not different per-VM but then I wonder if it wouldn't make more sense to set them per-provider or per-plan

**Comment by TylerGillson** [comment]
@ahadas thanks for considering it! I see your point about easing mass migrations. Putting the keys in the plan or provider makes sense to me, since multiple plans can be made if different keys exist for different datastores.
